### ISSUE TITLE
Audio becomes unavailable when switching modes while connected to the PC

### ISSUE THREAD

**Issue by yulius-fxpal** [ricohr/r-dk-firmware#1]
Firmware 1.1.0

1. Connect camera to PC (green light)
2. Change camera to HDMI mode (blue light)
3. Connect with console and change some settings
4. Change camera to USB mode (red light then green light again)
5. Notice audio is missing

The work around is to disconnect the camera when changing modes and reconnecting after the mode has changed.

**Comment by maruo2** [comment]
Thank you for your issue.
 
We reproduced your problem in our environment so we are going to detect causes and fix it.
For now, could you avoid the problem by adding the following steps to your procedure?
 
4. Select "File - Write as device startup settings" with the HDMI mode turned on. This step makes sure that the changed settings are saved.
5. Change camera to USB mode (red light then green light again)
6. Restart the camera. With this step, the audio should be available with the saved settings.

**Comment by maruo2** [comment]
This issue is fixed with v01.21, so I will close this issue.
